name: Update Dependency Graph

on:
    workflow_dispatch:

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Dependency Graph
        run: pip install -U pipdeptree && pipdeptree --warn silence --warn silence | awk -F'==' '{print $1}' | sort | uniq > dependencies.txt

      - name: Commit and push updated dependency file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dependencies.txt
          git commit -m "Update dependencies [skip ci]"
          git push
